package generator

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/Anhdeface/gmake/internal/models"
)

// GenerateMakefile generates a Makefile from the given config to the specified outputPath.
func GenerateMakefile(config *models.GomakeConfig, outputPath string) error {
	file, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to create Makefile: %w", err)
	}
	defer file.Close()

	var builder strings.Builder

	builder.WriteString("# ==========================================\n")
	builder.WriteString("# Generated by gomake\n")
	builder.WriteString("# Targets: ")
	builder.WriteString(strings.Join(config.Constants, ", "))
	builder.WriteString("\n# ==========================================\n\n")

	// Global targets
	var targetVars []string
	for _, c := range config.Constants {
		targetVars = append(targetVars, fmt.Sprintf("$(TARGET_%s)", c))
	}
	builder.WriteString(fmt.Sprintf("TARGETS = %s\n\n", strings.Join(targetVars, " ")))

	builder.WriteString(".PHONY: all clean")
	for _, c := range config.Constants {
		builder.WriteString(fmt.Sprintf(" %s", c))
	}

	// Add script names to PHONY if any
	var scriptNames []string
	for name := range config.Scripts {
		scriptNames = append(scriptNames, name)
	}
	sort.Strings(scriptNames)
	for _, name := range scriptNames {
		builder.WriteString(fmt.Sprintf(" %s", name))
	}
	builder.WriteString("\n\n")

	builder.WriteString("all: $(TARGETS)\n\n")

	for _, c := range config.Constants {
		builder.WriteString(fmt.Sprintf("%s: $(TARGET_%s)\n", c, c))
	}
	builder.WriteString("\n")

	// Generate rules for each target
	for _, c := range config.Constants {
		setup := config.Setups[c]
		dep := config.Dependencies[c]

		if setup == nil {
			setup = &models.ConfigSetup{}
		}
		if dep == nil {
			dep = &models.ConfigDependency{BuildType: "executable"}
		}

		builder.WriteString(fmt.Sprintf("# ==========================================\n"))
		builder.WriteString(fmt.Sprintf("# Target: %s\n", c))
		builder.WriteString(fmt.Sprintf("# ==========================================\n"))

		// Compiler Configuration
		if setup.Compiler == "" {
			setup.Compiler = "gcc"
		}
		builder.WriteString(fmt.Sprintf("CC_%s = %s\n", c, setup.Compiler))
		
		if setup.Flags != "" {
			builder.WriteString(fmt.Sprintf("CFLAGS_%s = %s\n", c, setup.Flags))
		}
		
		if len(dep.Includes) > 0 {
			var formattedIncludes []string
			for _, inc := range dep.Includes {
				if strings.HasPrefix(inc, "-I") {
					formattedIncludes = append(formattedIncludes, inc)
				} else {
					formattedIncludes = append(formattedIncludes, "-I"+inc)
				}
			}
			builder.WriteString(fmt.Sprintf("INCLUDES_%s = %s\n", c, strings.Join(formattedIncludes, " ")))
		}
		if dep.Libs != "" {
			builder.WriteString(fmt.Sprintf("LIBS_%s = %s\n", c, dep.Libs))
		}
		builder.WriteString("\n")

		// Source Files and Objects
		var processedSources []string
		for _, src := range dep.Sources {
			if strings.Contains(src, "*") {
				processedSources = append(processedSources, fmt.Sprintf("$(wildcard %s)", src))
			} else {
				processedSources = append(processedSources, src)
			}
		}
		
		if len(processedSources) > 0 {
			builder.WriteString(fmt.Sprintf("SRCS_%s = %s\n", c, strings.Join(processedSources, " ")))
		}

		if dep.ObjectDpdcy && len(processedSources) > 0 {
			builder.WriteString(fmt.Sprintf("OBJS_%s = $(addsuffix .%s.o, $(SRCS_%s))\n", c, c, c))
			builder.WriteString(fmt.Sprintf("DEPS_%s = $(OBJS_%s:.o=.d)\n", c, c))
		}
		builder.WriteString("\n")

		// Target name
		targetName := dep.Target
		if targetName == "" {
			targetName = setup.Name
		}
		if targetName == "" {
			targetName = c
		}
		builder.WriteString(fmt.Sprintf("TARGET_%s = %s\n\n", c, targetName))

		// Target rule
		builder.WriteString(fmt.Sprintf("$(TARGET_%s): ", c))
		if dep.ObjectDpdcy {
			builder.WriteString(fmt.Sprintf("$(OBJS_%s)\n", c))
		} else {
			builder.WriteString(fmt.Sprintf("$(SRCS_%s)\n", c))
		}
		
		if strings.Contains(targetName, "/") {
			builder.WriteString("\t@mkdir -p $(dir $@)\n")
		}

		// Link command
		var libsSuffix string
		if dep.Libs != "" {
			libsSuffix = fmt.Sprintf(" $(LIBS_%s)", c)
		}
		
		switch dep.BuildType {
		case "static":
			if dep.ObjectDpdcy {
				builder.WriteString(fmt.Sprintf("\tar rcs $@ $^\n\n"))
			} else {
				builder.WriteString(fmt.Sprintf("\tar rcs $@ $(SRCS_%s)\n\n", c))
			}
		case "shared":
			if dep.ObjectDpdcy {
				builder.WriteString(fmt.Sprintf("\t$(CC_%s) -shared $(CFLAGS_%s) $(INCLUDES_%s) -o $@ $^%s\n\n", c, c, c, libsSuffix))
			} else {
				builder.WriteString(fmt.Sprintf("\t$(CC_%s) -shared $(CFLAGS_%s) $(INCLUDES_%s) -o $@ $(SRCS_%s)%s\n\n", c, c, c, c, libsSuffix))
			}
		default: // "executable"
			if dep.ObjectDpdcy {
				builder.WriteString(fmt.Sprintf("\t$(CC_%s) $(CFLAGS_%s) $(INCLUDES_%s) -o $@ $^%s\n\n", c, c, c, libsSuffix))
			} else {
				builder.WriteString(fmt.Sprintf("\t$(CC_%s) $(CFLAGS_%s) $(INCLUDES_%s) -o $@ $(SRCS_%s)%s\n\n", c, c, c, c, libsSuffix))
			}
		}

		// Object compilation rule
		if dep.ObjectDpdcy {
			builder.WriteString(fmt.Sprintf("%%.c.%s.o: %%.c\n", c))
			builder.WriteString(fmt.Sprintf("\t$(CC_%s) $(CFLAGS_%s) $(INCLUDES_%s) -MMD -MP -c $< -o $@\n\n", c, c, c))
			builder.WriteString(fmt.Sprintf("%%.cpp.%s.o: %%.cpp\n", c))
			builder.WriteString(fmt.Sprintf("\t$(CC_%s) $(CFLAGS_%s) $(INCLUDES_%s) -MMD -MP -c $< -o $@\n\n", c, c, c))
			
			// Include dependencies
			builder.WriteString(fmt.Sprintf("-include $(DEPS_%s)\n\n", c))
		}
	}

	// Clean Rule
	builder.WriteString("# ==========================================\n")
	builder.WriteString("# Clean Rule\n")
	builder.WriteString("# ==========================================\n")
	builder.WriteString("clean:\n")
	
	var cleanTargets []string
	for _, c := range config.Constants {
		dep := config.Dependencies[c]
		if dep != nil && dep.ObjectDpdcy && len(dep.Sources) > 0 {
			cleanTargets = append(cleanTargets, fmt.Sprintf("$(OBJS_%s)", c), fmt.Sprintf("$(DEPS_%s)", c))
		}
	}
	cleanTargets = append(cleanTargets, "$(TARGETS)")
	builder.WriteString(fmt.Sprintf("\trm -f %s\n\n", strings.Join(cleanTargets, " ")))

	// Custom Scripts
	if len(scriptNames) > 0 {
		builder.WriteString("# ==========================================\n")
		builder.WriteString("# Custom Scripts\n")
		builder.WriteString("# ==========================================\n")
		for _, name := range scriptNames {
			command := config.Scripts[name]
			if name == "all" || name == "clean" || name == "TARGETS" {
				continue // Skip reserved names
			}
			builder.WriteString(fmt.Sprintf("%s:\n", name))
			builder.WriteString(fmt.Sprintf("\t%s\n\n", command))
		}
	}

	_, err = file.WriteString(builder.String())
	if err != nil {
		return fmt.Errorf("failed to write to Makefile: %w", err)
	}

	return nil
}
