package generator

import (
	"fmt"
	"os"
	"strings"

	"github.com/Anhdeface/gmake/internal/models"
)

// GenerateMakefile generates a Makefile from the given GomakeConfig.
func GenerateMakefile(config *models.GomakeConfig, outputFilePath string) error {
	var builder strings.Builder

	// Header
	builder.WriteString("# ==========================================\n")
	builder.WriteString("# Generated by gomake\n")
	if config.Dependency.Target != "" {
		builder.WriteString(fmt.Sprintf("# Target: %s\n", config.Dependency.Target))
	} else {
		builder.WriteString(fmt.Sprintf("# Target: %s\n", config.Setup.Name))
	}
	builder.WriteString("# ==========================================\n\n")

	// Compiler Configuration
	builder.WriteString("# --- Compiler Configuration ---\n")
	if config.Setup.Compiler != "" {
		builder.WriteString(fmt.Sprintf("CC = %s\n", config.Setup.Compiler))
	}
	if config.Setup.Flags != "" {
		builder.WriteString(fmt.Sprintf("CFLAGS = %s\n", config.Setup.Flags))
	}
	
	// Format INCLUDES
	if len(config.Dependency.Includes) > 0 {
		var formattedIncludes []string
		for _, inc := range config.Dependency.Includes {
			if strings.HasPrefix(inc, "-I") {
				formattedIncludes = append(formattedIncludes, inc)
			} else {
				formattedIncludes = append(formattedIncludes, "-I"+inc)
			}
		}
		builder.WriteString(fmt.Sprintf("INCLUDES = %s\n", strings.Join(formattedIncludes, " ")))
	}
	builder.WriteString("\n")

	// Source Files and Objects
	builder.WriteString("# --- Source Files and Objects ---\n")
	
	var processedSources []string
	for _, src := range config.Dependency.Sources {
		if strings.Contains(src, "*") {
			processedSources = append(processedSources, fmt.Sprintf("$(wildcard %s)", src))
		} else {
			processedSources = append(processedSources, src)
		}
	}
	
	if len(processedSources) > 0 {
		builder.WriteString(fmt.Sprintf("SRCS = %s\n", strings.Join(processedSources, " ")))
	}

	if config.Dependency.ObjectDpdcy && len(processedSources) > 0 {
		builder.WriteString("OBJS = $(SRCS:.c=.o)\n")
	}
	builder.WriteString("\n")

	// Target
	targetName := config.Dependency.Target
	if targetName == "" {
		targetName = config.Setup.Name
	}
	if targetName == "" {
		targetName = "app"
	}
	builder.WriteString(fmt.Sprintf("TARGET = %s\n\n", targetName))

	// Build Rules
	builder.WriteString("# --- Build Rules ---\n")
	builder.WriteString("all: $(TARGET)\n\n")

	// Target rule
	builder.WriteString("$(TARGET): ")
	if config.Dependency.ObjectDpdcy {
		builder.WriteString("$(OBJS)\n")
	} else {
		builder.WriteString("$(SRCS)\n")
	}
	
	// Create dir if target is in a subdirectory
	if strings.Contains(targetName, "/") {
		builder.WriteString("\t@mkdir -p $(dir $@)\n")
	}

	// Link command
	if config.Dependency.ObjectDpdcy {
		builder.WriteString("\t$(CC) $(CFLAGS) $(INCLUDES) -o $@ $^\n\n")
	} else {
		// Just compile directly from sources if ObjectDpdcy is disabled
		builder.WriteString("\t$(CC) $(CFLAGS) $(INCLUDES) -o $@ $(SRCS)\n\n")
	}

	// Object compilation rule (only if ObjectDpdcy is true)
	if config.Dependency.ObjectDpdcy {
		builder.WriteString("%.o: %.c\n")
		builder.WriteString("\t$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@\n\n")
	}

	// Clean Rule
	builder.WriteString("# --- Clean Rule ---\n")
	builder.WriteString("clean:\n")
	if config.Dependency.ObjectDpdcy {
		builder.WriteString("\trm -f $(OBJS) $(TARGET)\n")
	} else {
		builder.WriteString("\trm -f $(TARGET)\n")
	}

	// Write to file
	return os.WriteFile(outputFilePath, []byte(builder.String()), 0644)
}
